-- Core settings
require('keymaps')
require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
require('plugins.obsidian')
require('plugins.zenmode')
require('plugins.neogit')
require('plugins.codesnap')
require('plugins.harpoon')